apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploymennt
  labels:
    app: nginx-deploy
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          value: {{DB_URL}}
  replicas: 5
  selector:
    matchLabels:
      app: nginx